# Define all feeds in one section
[feeds]
coinbase_btc_usd = { exchange = "coinbase", base_currency = "BTC", quote_currency = "USD", enabled = true }
binance_btc_usd = { exchange = "binance", base_currency = "BTC", quote_currency = "USD", enabled = true }
coinbase_eth_usd = { exchange = "coinbase", base_currency = "ETH", quote_currency = "USD", enabled = true }
binance_eth_usd = { exchange = "binance", base_currency = "ETH", quote_currency = "USD", enabled = true }

# Define indices and reference feeds
[[indices]]
name = "BTC-USD-INDEX"
smoothing = "ema"  # Options: "none", "sma", "ema"
feeds = [
    { id = "coinbase_btc_usd", weight = 60 },
    { id = "binance_btc_usd", weight = 40 }
]

[[indices]]
name = "ETH-USD-INDEX"
smoothing = "sma"  # Options: "none", "sma", "ema"
feeds = [
    { id = "coinbase_eth_usd", weight = 50 },
    { id = "binance_eth_usd", weight = 50 }
]

[database]
enabled = false

[websocket]
address = "0.0.0.0:9000"
