# Define all feeds in one section
[feeds]
coinbase_btc_usd = { exchange = "coinbase", symbol = "BTC-USD", enabled = true }
binance_btc_usdt = { exchange = "binance", symbol = "BTCUSDT", enabled = false }  # Disabled feed
coinbase_eth_usd = { exchange = "coinbase", symbol = "ETH-USD", enabled = true }
binance_eth_usdt = { exchange = "binance", symbol = "ETHUSDT", enabled = true }

# Define indices and reference feeds
[[indices]]
name = "BTC-USD-INDEX"
smoothing = "ema"  # Options: "none", "sma", "ema"
feeds = [
    { id = "coinbase_btc_usd", weight = 100 }  # Only one feed with 100% weight
]

[[indices]]
name = "ETH-USD-INDEX"
smoothing = "sma"  # Options: "none", "sma", "ema"
feeds = [
    { id = "coinbase_eth_usd", weight = 50 },
    { id = "binance_eth_usdt", weight = 50 }
]

[database]
enabled = true
url = "postgres://postgres:password@localhost:5432/crypto_indices"
retention_days = 30  # How long to keep raw data

[websocket]
address = "0.0.0.0:9000"
