[[indices]]
name = "BTC-USD-INDEX"
smoothing = "none"  # Options: "none", "sma", "ema"

[[indices.feeds]]
id = "coinbase_btc_usd"
exchange = "coinbase"
symbol = "BTC-USD"
weight = 100  # 100% weight

[database]
enabled = false

[websocket]
address = "0.0.0.0:9001"
