version: '3.8'

services:
  # TimescaleDB for data persistence
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=crypto_indices
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Crypto Index Collector
  collector:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      - RUST_LOG=info
    volumes:
      - ./config.toml:/app/config.toml
    ports:
      - "9000:9000"
    restart: unless-stopped

volumes:
  timescaledb_data:
